---
- name: Create directory depends
  become: yes
  file:
    path: '{{ item }}'
    owner: nodepool
    group: nodepool
    mode: 0755
    state: directory
  with_items: '{{ directory_depends }}'

- name: Install nodepool configuration
  become: yes
  template:
    src: '{{ item }}'
    dest: '/{{ item }}'
    owner: nodepool
    group: nodepool
    mode: 0644
  with_items: '{{ config_files }}'

- name: Git clone project-config
  become: yes
  git:
    repo: https://git.openstack.org/openstack-infra/project-config
    dest: '{{ project_config_src_dir }}'

- name: Copy elements from project-config into place
  become: yes
  synchronize:
    src: '{{ project_config_src_dir }}/nodepool/elements/'
    dest: /etc/nodepool/elements/
    recursive: yes
    rsync_opts: '--chown=nodepool:nodepool'
  delegate_to: '{{ ansible_host }}'
