---
- name: Create group account
  become: yes
  group:
    name: nodepool

- name: Create user account
  become: yes
  user:
    name: nodepool
    group: nodepool
    home: /home/nodepool
    createhome: yes

- name: Install apt packages
  become: yes
  apt:
    name: '{{ apt_depends }}'
    update_cache: yes
    state: latest
