---
- name: Install apt packages
  become: yes
  apt:
    name: ['mariadb-server', 'mariadb-client', 'libmariadb-client-lgpl-dev']
    update_cache: yes

- name: Create symbolic link for mysql_config
  become: yes
  file:
    src: /usr/bin/mariadb_config
    dest: /usr/bin/mysql_config
    state: link

- name: Install pip packages
  become: yes
  pip:
    name: 'MySQL-python'

- name: Copy mysql_secure_installation.sql into place
  become: yes
  copy:
    src: mysql_secure_installation.sql
    dest: /tmp/mysql_secure_installation.sql
    mode: 0400
  notify:
    - Execute mysql secure installation
