---
nodepool_src_dir: '{{ ansible_user_dir }}/src/git.openstack.org/openstack-infra/nodepool'

directory_depends:
  - /etc/nodepool
  - /etc/nodepool/elements
  - /opt/dib_tmp
  - /opt/dib_cache
  - /var/log/nodepool
  - /etc/openstack

config_files:
  - etc/nodepool/builder-logging.conf
  - etc/nodepool/launcher-logging.conf
  - etc/nodepool/nodepool.yaml
  - etc/nodepool/repos.yaml
  - etc/clouds.yaml

systemd_files:
  - etc/systemd/system/nodepool-builder.service
  - etc/systemd/system/nodepool-launcher.service

nodepool_services:
  - nodepool-builder
  - nodepool-launcher
