---
root_dir: '{{ lookup("pipe", "pwd") | dirname }}'

apt_depends:
  - dbus
  - libffi-dev
  - libssl-dev
  - build-essential
  - python3-dev
  - python-dev
  - python3-pip
  - python-pip

pip_depends:
  - setuptools
